AWSTemplateFormatVersion: '2010-09-09'
Description: Create a VPC, Subnet, Security Group, and EC2 instance

Parameters:
  KeyName:
    Description: EC2 SSH key pair name
    Type: AWS::EC2::KeyPair::KeyName
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues: [t2.micro, t2.small, t2.medium]

Resources:
  # 1. 创建虚拟网络 VPC
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16

  # 2. 在 VPC 内创建子网
  MySubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.0.1.0/24

  # 3. 建立 Security Group，允许 SSH (22), HTTP (80)
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and HTTP access
      VpcId: !Ref MyVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  # 4. 创建 EC2 实例，分配到上述子网 & 安全组
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: ami-0d5eff06f840b45e9  # 美东示例 AMI
      SubnetId: !Ref MySubnet
      SecurityGroupIds:
        - !Ref MySecurityGroup

Outputs:
  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref MyEC2Instance
  PublicIP:
    Description: EC2 Public IP
    Value: !GetAtt MyEC2Instance.PublicIp



    Mappings:
      EnvConfig:
        Dev:
          InstanceType: "t3.micro"  # 开发环境用小实例
          AMI: "ami-dev-123"
        Prod:
          InstanceType: "t3.small"  # 生产环境用较大实例
          AMI: "ami-prod-456"

    Parameters:
      Environment:
        Type: String
        AllowedValues: [ "Dev", "Prod" ]
        Default: "Dev"

    Resources:
      EC2Instance:
        Type: AWS::EC2::Instance
        Properties:
          InstanceType: !FindInMap [ EnvConfig, !Ref Environment, InstanceType ]  # 动态获取实例类型
          ImageId: !FindInMap [ EnvConfig, !Ref Environment, AMI ]  # 动态获取AMI
          KeyName: !Ref KeyPairName  # 引用参数传入的密钥对
